AnimalShelter/Models/Animal.cs
namespace AnimalShelter.Models 
{
  public class Animal
  {
    public string Name { get; set; }
    public string Breed { get; set; }
    public string Type { get; set; }
    public int DateOfAdmittanceMonth { get; set; }
    public int DateOfAdmittanceDay { get; set; }
    public int DateOfAdmittanceYear { get; set; }
    public int AnimalId { get; set; }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }

    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    public ActionResult Edit(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    [HttpPost]
    public ActionResult Edit(Animal animal)
    {
      _db.Animals.Update(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault( animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault( animal => animal.AnimalId == id);
      _db.Animals.Remove(thisAnimal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @model AnimalShelter.Models.Animal

  <h3>Add a new Animal</h3>
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Type)
    @Html.TextBoxFor(model => model.Type)
    <br>
    @Html.LabelFor(model => model.Breed)
    @Html.TextBoxFor(model => model.Breed)
    <br>
    @Html.LabelFor(model => model.DateOfAdmittanceMonth)
    @Html.TextBoxFor(model => model.DateOfAdmittanceMonth, new { type = "number", min = "1", max = "12", step = "1" })
    @Html.LabelFor(model => model.DateOfAdmittanceDay)
    @Html.TextBoxFor(model => model.DateOfAdmittanceDay, new { type = "number", min = "1", max = "31", step = "1" })
    @Html.LabelFor(model => model.DateOfAdmittanceYear)
    @Html.TextBoxFor(model => model.DateOfAdmittanceYear, new { type = "number", min = "1990", max = "2022", step = "1" })
    <input type="submit" value="Add a new furry friend"/>
  }

  <p>@Html.ActionLink("Show all animals!", "Index")</p>
</div>

AnimalShelter/Views/Animals/Delete.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List!", "Index")

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Furry Friend Details</h2>
<hr>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)<h3>
<h3>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)<h3>
<h3>Date of Admittance: @Html.DisplayFor(model => model.DateOfAdmittanceMonth)/@Html.DisplayFor(model => model.DateOfAdmittanceDay)/@Html.DisplayFor(model => model.DateOfAdmittanceYear)<h3>
<hr>
<p>@Html.ActionLink("Back to list!", "Index")</p>
<p>@Html.ActionLink("Edit Animal Info", "Edit", new { id = Model.AnimalId })</p>
<p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.AnimalId })</p>

AnimalShelter/Views/Animals/Edit.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Edit</h2>

<h4>Edit this animal's info: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.AnimalId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Type)
  @Html.EditorFor(model => model.Type)
  <br>
  @Html.LabelFor(model => model.Breed)
  @Html.EditorFor(model => model.Breed)
  <br>
  @Html.LabelFor(model => model.DateOfAdmittanceMonth)
  @Html.TextBoxFor(model => model.DateOfAdmittanceMonth, new { type = "number", min = "1", max = "12", step = "1" })
  @Html.LabelFor(model => model.DateOfAdmittanceDay)
  @Html.TextBoxFor(model => model.DateOfAdmittanceDay, new { type = "number", min = "1", max = "31", step = "1" })
  @Html.LabelFor(model => model.DateOfAdmittanceYear)
  @Html.TextBoxFor(model => model.DateOfAdmittanceYear, new { type = "number", min = "1990", max = "2022", step = "1" })
  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @using AnimalShelter.Models;

  <h1>Animals</h1>

  @if (@Model.Count == 0)
  {
    <h3>No furry friends yet</h3>
  }

  <ul>
  @foreach(Animal animal in Model)
    {
      <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.AnimalId})</li>
    }
  </ul>

  <p>@Html.ActionLink("Add an animal!", "Create")</p>
</div>

AnimalShelter/Views/Home/index.cshtml
@{
  Layout = "_Layout";
}

<h1>Animal Shelter</h1>
<p>@Html.ActionLink("Click to see which furry friend you can adpot today! ", "Index", "Animals")

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link 
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>